[package]
name = "btc-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
bitcoin = "0.31"
clap = { version = "4", features = ["derive"] }
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["json"]
