[package]
name = "btc-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
bitcoin = "0.31"
hex = "0.4.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["json"]
